version: '3.8'
services:
  redis-server:
    image: 'redis'
    ports:
    - "6379:6379"
    command: [ "redis-server", "--protected-mode", "no"]
  kotlin-app:
    build: .
    ports:
      - "9000:8080"
    links:
      - redis-server